### ISSUE TITLE
[Feature Request] Reorder Toggles in the Admin Interface

### ISSUE THREAD

**Issue by rurre** [jangxx/VRC-Avatar-Remote-Server#1]
I'd like to be able to reorder toggles in the admin interface.

**Comment by jangxx** [comment]
Added in e4fceca87891e43b34d0c633db4b28c30b66c9b5

**Comment by rurre** [comment]
Thank you. Only had a chance to test it now. A lot more usable now that I don't have to delete and recreate toggles to reorder, or dig throug the config!
