### ISSUE TITLE
[Feature Request] Duplicate a Board

### ISSUE THREAD

**Issue by rurre** [jangxx/VRC-Avatar-Remote-Server#2]
I'd like to be able to duplicate boards so I can, for example, have a public board and a private one that has a few extra toggles.

**Comment by jangxx** [comment]
Added in ebbc07a885f3e1fb40cfe7b63fbe2a51b1032f1e

**Comment by rurre** [comment]
I just noticed that duplicating a board seems to reset(?) the order for my avatars.

**Comment by jangxx** [comment]
That's true, I forgot to copy the order to the new board (or rather I forgot to replace the old control ids in the order array with the new ones).

**Comment by jangxx** [comment]
Fixed in 445d76b015f89b4d68ba8f459d709e0adcd12131
