### ISSUE TITLE
[Feature Request] Duplicate control

### ISSUE THREAD

**Issue by rurre** [jangxx/VRC-Avatar-Remote-Server#4]
I'd like an option to duplicate a control and order it right after the one that got duplicated (saves having to drag around in big boards). 
It's useful when doing int toggles, like in this case where I have a bunch of phone wallpapers.

![image](https://user-images.githubusercontent.com/16716633/210184251-4176a338-b8fb-4be2-b5c9-70ce2687407a.png)

**Comment by jangxx** [comment]
Added in a4b90094632ec7d27a904df6506ff25669983a75, but I would be careful with updating already, since things are still largely untested,

**Comment by rurre** [comment]
Neat. I'll wait for headers first tho because my current setup is largely complete.
________________________________
